# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StatusWidgetUi.ui'
#
# Created: Thu Aug 14 03:01:52 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Status(object):
    def setupUi(self, Status):
        Status.setObjectName(_fromUtf8("Status"))
        Status.resize(618, 198)
        self.gridLayout = QtGui.QGridLayout(Status)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_3 = QtGui.QGroupBox(Status)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lbl_dev_name = QtGui.QLabel(self.groupBox_3)
        self.lbl_dev_name.setObjectName(_fromUtf8("lbl_dev_name"))
        self.gridLayout_3.addWidget(self.lbl_dev_name, 5, 2, 1, 1)
        self.lbl_model_lbl = QtGui.QLabel(self.groupBox_3)
        self.lbl_model_lbl.setObjectName(_fromUtf8("lbl_model_lbl"))
        self.gridLayout_3.addWidget(self.lbl_model_lbl, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 6, 1, 1)
        self.lbl_local = QtGui.QLabel(self.groupBox_3)
        self.lbl_local.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_local.setObjectName(_fromUtf8("lbl_local"))
        self.gridLayout_3.addWidget(self.lbl_local, 1, 2, 1, 1)
        self.lbl_fw_ver = QtGui.QLabel(self.groupBox_3)
        self.lbl_fw_ver.setObjectName(_fromUtf8("lbl_fw_ver"))
        self.gridLayout_3.addWidget(self.lbl_fw_ver, 6, 2, 1, 1)
        self.lbl_serial_lbl = QtGui.QLabel(self.groupBox_3)
        self.lbl_serial_lbl.setObjectName(_fromUtf8("lbl_serial_lbl"))
        self.gridLayout_3.addWidget(self.lbl_serial_lbl, 7, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 1, 1, 3, 1)
        self.line_5 = QtGui.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_3.addWidget(self.line_5, 1, 5, 3, 1)
        self.lbl_external = QtGui.QLabel(self.groupBox_3)
        self.lbl_external.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_external.setObjectName(_fromUtf8("lbl_external"))
        self.gridLayout_3.addWidget(self.lbl_external, 1, 0, 1, 1)
        self.lbl_remote = QtGui.QLabel(self.groupBox_3)
        self.lbl_remote.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_remote.setObjectName(_fromUtf8("lbl_remote"))
        self.gridLayout_3.addWidget(self.lbl_remote, 1, 4, 1, 1)
        self.lbl_output_icon = QtGui.QLabel(self.groupBox_3)
        self.lbl_output_icon.setText(_fromUtf8(""))
        self.lbl_output_icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/enabled_false.png")))
        self.lbl_output_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_output_icon.setObjectName(_fromUtf8("lbl_output_icon"))
        self.gridLayout_3.addWidget(self.lbl_output_icon, 3, 6, 1, 1)
        self.lbl_fwver_lbl = QtGui.QLabel(self.groupBox_3)
        self.lbl_fwver_lbl.setObjectName(_fromUtf8("lbl_fwver_lbl"))
        self.gridLayout_3.addWidget(self.lbl_fwver_lbl, 6, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.groupBox_3)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_3.addWidget(self.line_7, 2, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 1, 1)
        self.line_8 = QtGui.QFrame(self.groupBox_3)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_3.addWidget(self.line_8, 2, 6, 1, 1)
        self.line_4 = QtGui.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 1, 3, 3, 1)
        self.line_6 = QtGui.QFrame(self.groupBox_3)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 2, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.push_REN = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_REN.sizePolicy().hasHeightForWidth())
        self.push_REN.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/enabled_false.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/enabled_true.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.push_REN.setIcon(icon)
        self.push_REN.setCheckable(True)
        self.push_REN.setObjectName(_fromUtf8("push_REN"))
        self.horizontalLayout.addWidget(self.push_REN)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 4, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 10, 0, 1, 7)
        self.lbl_external_icon = QtGui.QLabel(self.groupBox_3)
        self.lbl_external_icon.setText(_fromUtf8(""))
        self.lbl_external_icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/enabled_false.png")))
        self.lbl_external_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_external_icon.setObjectName(_fromUtf8("lbl_external_icon"))
        self.gridLayout_3.addWidget(self.lbl_external_icon, 3, 0, 1, 1)
        self.lbl_serial_num = QtGui.QLabel(self.groupBox_3)
        self.lbl_serial_num.setObjectName(_fromUtf8("lbl_serial_num"))
        self.gridLayout_3.addWidget(self.lbl_serial_num, 7, 2, 1, 1)
        self.lbl_local_icon = QtGui.QLabel(self.groupBox_3)
        self.lbl_local_icon.setText(_fromUtf8(""))
        self.lbl_local_icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/enabled_false.png")))
        self.lbl_local_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_local_icon.setObjectName(_fromUtf8("lbl_local_icon"))
        self.gridLayout_3.addWidget(self.lbl_local_icon, 3, 2, 1, 1)
        self.line_9 = QtGui.QFrame(self.groupBox_3)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_3.addWidget(self.line_9, 4, 0, 1, 7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_laser_warning = QtGui.QLabel(self.groupBox_3)
        self.lbl_laser_warning.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_laser_warning.sizePolicy().hasHeightForWidth())
        self.lbl_laser_warning.setSizePolicy(sizePolicy)
        self.lbl_laser_warning.setMaximumSize(QtCore.QSize(64, 64))
        self.lbl_laser_warning.setText(_fromUtf8(""))
        self.lbl_laser_warning.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/laser_warning.svg")))
        self.lbl_laser_warning.setScaledContents(True)
        self.lbl_laser_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_laser_warning.setObjectName(_fromUtf8("lbl_laser_warning"))
        self.horizontalLayout_2.addWidget(self.lbl_laser_warning)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 5, 5, 4, 2)
        self.lbl_fps = QtGui.QLabel(self.groupBox_3)
        self.lbl_fps.setObjectName(_fromUtf8("lbl_fps"))
        self.gridLayout_3.addWidget(self.lbl_fps, 8, 2, 1, 1)
        self.lbl_fps_lbl = QtGui.QLabel(self.groupBox_3)
        self.lbl_fps_lbl.setObjectName(_fromUtf8("lbl_fps_lbl"))
        self.gridLayout_3.addWidget(self.lbl_fps_lbl, 8, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.retranslateUi(Status)
        QtCore.QMetaObject.connectSlotsByName(Status)

    def retranslateUi(self, Status):
        Status.setWindowTitle(_translate("Status", "Form", None))
        self.groupBox_3.setTitle(_translate("Status", "Status", None))
        self.lbl_dev_name.setText(_translate("Status", "NO_CONN", None))
        self.lbl_model_lbl.setText(_translate("Status", "Device:", None))
        self.label_4.setText(_translate("Status", "= Output", None))
        self.lbl_local.setText(_translate("Status", "Local ", None))
        self.lbl_fw_ver.setText(_translate("Status", "NO_CONN", None))
        self.lbl_serial_lbl.setText(_translate("Status", "Serial:", None))
        self.lbl_external.setText(_translate("Status", "External", None))
        self.lbl_remote.setText(_translate("Status", "Remote", None))
        self.lbl_fwver_lbl.setText(_translate("Status", "FWver:  ", None))
        self.lbl_serial_num.setText(_translate("Status", "NO CONN", None))
        self.lbl_fps.setText(_translate("Status", "0 Hz", None))
        self.lbl_fps_lbl.setText(_translate("Status", "Cadence:", None))

import icons_rc
